---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
  flake8 library --ignore=E501,E402
platforms:
  - name: mongo1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ${MOLECULE_COMMAND:-/usr/sbin/init}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true
    privileged: true
    cgroupns_mode: host
    capabilities:
      - SYS_ADMIN
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    groups:
      - mongo_master
provisioner:
  name: ansible
  config_options:
    defaults:
      pipelining: true
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
    prepare:  ${MOLECULE_PLAYBOOK:-prepare.yml}
  env:
    MONGODB_VERSION: ${MONGODB_VERSION:-6.0}
    MONGODB_PACKAGE: ${MONGODB_PACKAGE:-mongodb-org}
    AUTH_STATE: ${AUTH_STATE:-disabled}
  inventory:
    host_vars:
      mongo1:
        ansible_python_interpreter: auto_silent
        mongodb_net_bindip: "{{ hostvars[inventory_hostname].ansible_default_ipv4.address }},127.0.0.1"
        mongodb_master: true
verifier:
  name: ansible
scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
